# Generated by Django 5.0.7 on 2024-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0002_contact_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
